# Configuração do Dependabot para Git Hooks Central
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Manter pre-commit atualizado
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    assignees:
      - "pcnuness"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    ignore:
      # Ignorar atualizações major que podem quebrar compatibilidade
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Manter GitHub Actions atualizadas
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    assignees:
      - "pcnuness"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Manter dependências do npm (se houver)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    assignees:
      - "pcnuness"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignorar atualizações major
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
