- id: branch-ahead-check
  name: Verifica se a branch está atualizada em relação à default
  entry: hooks/branch_ahead_check.sh
  language: script
  stages: [pre-push]
  pass_filenames: false

- id: audit-trail
  name: Salva resultado auditável para o CI
  entry: hooks/audit_trail.sh
  language: script
  stages: [pre-push]
  pass_filenames: false

- id: secrets-detection-gitlab
  name: Secrets Detection (GitLab Analyzer)
  description: Detecta segredos usando a imagem Docker oficial do GitLab Analyzer (Multi-OS)
  entry: hooks/secrets_detection_wrapper.sh
  language: script
  stages: [pre-push]
  always_run: true
  pass_filenames: false
