- id: branch-ahead-check
  name: Verifica se a branch está atualizada em relação à default
  entry: hooks/branch_ahead_check.sh
  language: script
  stages: [pre-push]
  pass_filenames: false

- id: audit-trail
  name: Salva resultado auditável para o CI
  entry: hooks/audit_trail.sh
  language: script
  stages: [pre-push]
  pass_filenames: false

- id: secrets-detection-company-bash
  name: Secrets Detection (GitLab Analyzer)
  description: Detecta segredos usando a imagem Docker oficial do GitLab Analyzer (Python Multi-OS)
  entry: hooks/secrets_detection_wrapper.bash
  language: script
  stages: [pre-push]
  always_run: true
  pass_filenames: false

- id: secrets-detection-company-python
  name: Secrets Detection (GitLab Analyzer)
  description: Detecta segredos usando a imagem Docker oficial do GitLab Analyzer (Python Multi-OS)
  entry: hooks/secrets_detection_wrapper.py
  language: script
  stages: [pre-push]
  always_run: true
  pass_filenames: false

- id: gitleaks-docker
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: zricethezav/gitleaks git --pre-commit --redact --staged --verbose
  language: docker_image
  pass_filenames: false
