# Modelo de configuração pre-commit para projetos Node.js
# Copie este arquivo para .pre-commit-config.yaml e ajuste conforme necessário

repos:
  # Hooks nativos e rápidos (obrigatórios)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-push]
      - id: check-json
        stages: [pre-push]
      - id: check-yaml
        stages: [pre-push]
      - id: detect-private-key
        stages: [pre-push]

  # Catálogo central de hooks de segurança (SEMPRE usar tag específica)
  - repo: https://github.com/pcnuness/git-hooks-central.git
    rev: v1.0.3
    hooks:
      - id: security-pre-push-hook
        stages: [pre-push]
        always_run: true
        pass_filenames: false
      
      - id: branch-ahead-check
        stages: [pre-push]
        pass_filenames: false
      
      - id: deps-audit-fast
        stages: [pre-push]
        pass_filenames: false
      
      - id: audit-trail
        stages: [pre-push]
        pass_filenames: false

  # Hooks específicos para Node.js (ESLint moderno)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.34.0
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@9.9.0', '@eslint/js', 'globals']
        files: \.(js|jsx|ts|tsx)$
        stages: [pre-push]
        args: [--fix]

  # Validação de lock files (opcional)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-push]
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md)$
        args: [--write]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [pre-push]
