# Modelo de configuração pre-commit para projetos Java
# Copie este arquivo para .pre-commit-config.yaml e ajuste conforme necessário

repos:
  # Hooks nativos e rápidos (obrigatórios)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-push]
      - id: check-xml
        stages: [pre-push]
      - id: check-yaml
        stages: [pre-push]
      - id: detect-private-key
        stages: [pre-push]
      - id: detect-secrets
        stages: [pre-push]
        args: [--baseline, .secrets.baseline]

  # Catálogo central de hooks de segurança (SEMPRE usar tag específica)
  - repo: https://github.com/pcnuness/git-hooks-central.git
    rev: v1.0.3
    hooks:
      - id: security-pre-push-hook
        stages: [pre-push]
        always_run: true
        pass_filenames: false
      
      - id: branch-ahead-check
        stages: [pre-push]
        pass_filenames: false
      
      - id: deps-audit-fast
        stages: [pre-push]
        pass_filenames: false
      
      - id: audit-trail
        stages: [pre-push]
        pass_filenames: false

  # Hooks específicos para Java (opcional)
  - repo: https://github.com/pre-commit/mirrors-checkstyle
    rev: v10.12.5
    hooks:
      - id: checkstyle
        stages: [pre-push]
        files: \.(java)$
        args: [--config, hooks/java-security-config.yaml]

  # Validação de XML (Maven/Gradle)
  - repo: https://github.com/pre-commit/mirrors-xmllint
    rev: v1.0.0
    hooks:
      - id: xmllint
        stages: [pre-push]
        files: \.(xml)$
        args: [--schema, hooks/java-security-config.yaml]

  # Formatação de código (opcional)
  - repo: https://github.com/pre-commit/mirrors-google-java-format
    rev: v0.10.0
    hooks:
      - id: google-java-format
        stages: [pre-push]
        files: \.(java)$
        args: [--aosp]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [pre-push]
